### ISSUE TITLE
Refactor `reporter/index.js` to not cause side effects

### ISSUE THREAD

**Issue by coditva** [postmanlabs/newman-dashboard#13]
Currently `reporter/index.js` file causes side-effects on import (socket connection).
Refactor it such that it exposes a module that makes the side-effects explicit.

Could be something like a module in lib that has a `start` or `init` method that is called in the `index.js` file? This would also enable us to write better unit tests with fewer stubs.

**Comment by elit-altum** [comment]
So an ```init``` function, which can start the socket connection and pass on the socket to ```reporter/index``` ?

**Comment by elit-altum** [comment]
Fixed via https://github.com/elit-altum/newman-dashboard/pull/12
