### ISSUE TITLE
Tests for CLI start the dashboard process

### ISSUE THREAD

**Issue by coditva** [postmanlabs/newman-dashboard#15]
When the CLI tests are running, the dashboard is started and we get a message "Dashboard is running on port 5001".
The test should either prevent starting the process or terminate it properly.

**Comment by elit-altum** [comment]
Fixed this! I have multiple solutions for solving this one, will send the finalized one with PR#5

**Comment by elit-altum** [comment]
Fixed via https://github.com/elit-altum/newman-dashboard/pull/12
